version: '2'
services:
  jenkins:
    image: sadofrazer/jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    privileged: true
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
volumes:
  jenkins_home:
    driver: local